### ISSUE TITLE
Hit, Stay, Double Down, and Split

### ISSUE THREAD

**Issue by Dioxu** [cs361-W16/Blackjack-8#11]
The user could press the button hit and have one card dealt to their hand. The user could press the button stay, have no more cards added, and their turn ended. The user could press the button double down, have their bet doubled, and then receive one more card before having to stay on that total. The user could press the button split, if they start with two cards of the same rank, and then get to play two separate games against the dealer. This will also double their bet for the second hand.

**Comment by longmane** [comment]
All buttons are finally functional, user can split deck
